---

- name: Create Sozu Config File
  template:
    src: "{{ sozu.config.config_file }}.j2"
    dest: "{{ sozu.config.config_file_path }}/{{ sozu.config.config_file }}"
    owner: "{{ sozu.config.owner }}"
    group: "{{ sozu.config.owner }}"
    mode: 0644
  when: ansible_hostname == "sozu"

- name: Create Sozu Service File
  template:
    src: "{{ sozu.config.service_file }}.j2"
    dest: "{{ sozu.config.service_path }}/{{ sozu.config.service_file }}"
    owner: "{{ sozu.config.owner }}"
    group: "{{ sozu.config.owner }}"
    mode: 0644
  when: ansible_hostname == "sozu"
  notify: Start Sozu
