---

- include_tasks: debian.yml
  when: ansible_os_family == "Debian" 

- include_tasks: ubuntu.yml
  when: ansible_os_family == "Ubuntu" 

- include_tasks: centos.yml
  when: ansible_os_family == "RedHat" 
