---

- name: Install Java
  include_tasks: java.yml

- name: Install Cassandra
  include_tasks: archive_cassandra.yml
  when: ansible_os_family != "Debian" or ansible_os_family != "RedHat"

- name: Install Cassandra
  include_tasks: debian_cassandra.yml
  when: ansible_os_family == "Debian"

- name: Install Cassandra
  include_tasks: redhat_cassandra.yml
  when: ansible_os_family == "RedHat"