---

- name: Install Java
  yum:
    name: java-1.8.0
    state: installed

- name: Add Rundeck repo
  yum_repository:
    name: rundeck
    baseurl: http://repo.rundeck.org/latest.rpm
    enabled: yes

- name: Install Rundeck
  yum:
    name: rundeck
    state: installed
  notify: Start Rundeck