---

- name: Kibana Installation - Debian
  sudo: yes
  vars:
    version: 6.2.4
  apt: deb="https://artifacts.elastic.co/downloads/kibana/kibana-{{ version }}-amd64.deb" state="installed"
  when: ansible_os_family == "Debian"
  notify: Start Kibana

- name: Kibana Installation - RedHat
  sudo: yes
  vars:
    version: 6.2.4
  yum: name="https://artifacts.elastic.co/downloads/kibana/kibana-{{ version }}-x86_64.rpm" state="installed"
  when: ansible_os_family == "RedHat"
  notify: Start Kibana
