---
# tasks file for prometheus

- name: Create group
  group:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - prometheus

- name: Create Users
  become: true
  user:
    createhome: false
    groups: "{{ item.groups }}"
    name: "{{ item.users }}"
    shell: "/bin/false"
    state: present
  with_items:
    - {users: "prometheus", groups: "prometheus"}
    - {users: "node-exporter", groups: "prometheus"}

- name: "Create Directories"
  become: true
  file:
    force: true
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    path: "{{ item.path }}"
    state: directory
  with_items:
    - {path: "{{ path }}", owner: "prometheus", group: "prometheus", mode: "0755"}

- name: "Install Prometheus"
  become: true
  unarchive:
    dest: /opt/
    group: root
    owner: root
    src: "/opt/{{ prometheus.url }}{{ prometheus.version }}/{{ prometheus.package }}"
    remote_src: true

- name: Create Symbolic Link for Prometheus Directory
  become: true
  file:
    src: "{{ prometheus.package | basename | regex_replace('.tar.gz','') }}"
    dest: "/opt/prometheus"
    owner: "{{ users }}"
    group: "{{ groups }}"
    state: link

- name: Configure Prometheus
  become: true
  template:
    backup: true
    dest: "{{ item.dest }}/{{ item.src | basename | regex_replace('.j2','') }}"
    force: true
    group: "{{ item.group }}"
    owner: "{{ item.owner }}"
    src: "{{ item.src }}"
  with_items:
    - {src: "prometheus.yml.j2", group: "prometheus", owner: "prometheus", dest: "/etc/prometheus/"}
    - {src: "prometheus.service.j2", group: "root", owner: "root", dest: "/lib/systemd/system/"}
  notify: Start prometheus
