---
# tasks file for prometheus

- name: Create group
  group:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - prometheus

- name: Create Users
  become: true
  user:
    createhome: false
    groups: "{{ item.groups }}"
    name: "{{ item.users }}"
    shell: "/bin/false"
    state: present
  with_items:
    - {users: "prometheus", groups: "prometheus"}
    - {users: "node-exporter", groups: "prometheus"}

- name: "Create Directories"
  become: true
  file:
    force: true
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    path: "{{ item.path }}"
    state: directory
  with_items:
    - {path: "{{ path }}", owner: "prometheus", group: "prometheus", mode: "0755"}

- name: "Install Prometheus"
  become: true
  unarchive:
    dest: /opt/
    group: root
    owner: root
    src: "{{ url }}"
    remote_src: true

- name: Create Directories
  become: true
  file:
    force: true
    group: "{{ item.group }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
    path: "{{ item.path }}"
    state: directory
  with_items:
    - {path: "/etc/prometheus/consoles", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {path: "/etc/prometheus/consoles_librairies", group: "prometheus", owner: "prometheus", mode: "0755"}

- name: "Move files"
  become: true
  copy:
    dest: "{{ item.dest }}"
    force: true
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    remote_src: true
    src: "{{ item.src }}"
  with_items:
    - {src: "/opt/prometheus-2.3.1.linux-amd64/prometheus", dest: "/usr/local/bin", group: "prometheus", owner: "prometheus", mode: "0777"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/promtool", dest: "/usr/local/bin", group: "prometheus", owner: "prometheus", mode: "0777"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/console_libraries/menu.lib", dest: "/etc/prometheus/console_librairies", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/console_libraries/prom.lib", dest: "/etc/prometheus/console_librairies", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/consoles/index.html.example", dest: "/etc/prometheus/consoles", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/consoles/node-cpu.html", dest: "/etc/prometheus/consoles", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/consoles/node-disk.html", dest: "/etc/prometheus/consoles", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/consoles/node.html", dest: "/etc/prometheus/consoles", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/consoles/node-overview.html", dest: "/etc/prometheus/consoles", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/consoles/prometheus.html", dest: "/etc/prometheus/consoles", group: "prometheus", owner: "prometheus", mode: "0755"}
    - {src: "/opt/prometheus-2.3.1.linux-amd64/consoles/prometheus-overview.html", dest: "/etc/prometheus/consoles", group: "prometheus", owner: "prometheus", mode: "0755"}

- name: Configure Prometheus
  become: true
  template:
    backup: true
    dest: "{{ item.dest }}"
    force: true
    group: "{{ item.group }}"
    owner: "{{ item.owner }}"
    src: "{{ item.src }}"
  with_items:
    - {src: "prometheus.yml.j2", group: "prometheus", owner: "prometheus", dest: "/etc/prometheus/prometheus.yml"}
    - {src: "prometheus.service.j2", group: "root", owner: "root", dest: "/lib/systemd/system/prometheus.service"}
  notify: Start prometheus
