---

- name: Start InfluxDB
  systemd:
    name: influxdb
    state: started
    daemon_reload: yes

- name: Stop InfluxDB
  systemd:
    name: influxdb
    state: stopped
    daemon_reload: yes

- name: Start Grafana
  systemd:
    name: grafana
    state: started
    daemon_reload: yes

- name: Stop Grafana
  systemd:
    name: grafana
    state: stopped
    daemon_reload: yes

- name: Stop Nginx
  systemd:
    name: nginx
    state: stopped
    daemon_reload: yes

- name: Start Nginx
  systemd:
    name: nginx
    state: started
    daemon_reload: yes

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
