---
# defaults file for prometheus

user: "root"
group: "root"

prometheus_version: "2.10.0"

prometheus:
  url: "https://github.com/prometheus/prometheus/releases/download"
  package: "prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
  data_dir: /var/lib/prometheus
  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  alertmanager_config: []
  alert_relabel_configs: []
  remote_write: []
  remote_read: []
  rules_files: []
  external_labels:
    environment: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"
  targets: {}

# Alternative config file name, searched in ansible templates path.
prometheus_config_file: 'prometheus.yml.j2'

prometheus_alert_rules_files:
  - prometheus/rules/*.rules

prometheus_static_targets_files:
  - prometheus/targets/*.yml
  - prometheus/targets/*.json
