---
# handlers file for prometheus

- name: Start prometheus
  become: true
  systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true

- name: Stop prometheus
  become: true
  systemd:
    name: prometheus
    state: stopped

- name: Restart prometheus
  become: true
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: Node-Exporter Start
  become: true
  systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true

- name: Node-Exporter Stop
  become: true
  systemd:
    name: node_exporter
    state: stopped

- name: Node-Exporter Restart
  become: true
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true
